source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'InterstitialAdControllerCocos2d_Tests', :exclusive => true do
  pod "InterstitialAdControllerCocos2d", :path => "../"

  
end
